# Best job.

- type: job
  id: ChiefMedicalOfficer
  name: job-name-cmo
  description: job-description-cmo
  playTimeTracker: JobChiefMedicalOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 18000 #5 hrs # Vanilla-RoleTime
#    - !type:OverallPlaytimeRequirement
#      time: 144000 #40 hrs
  weight: 10
  startingGear: CMOGear
  icon: "JobIconChiefMedicalOfficer"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: Skill
        RangeWeaponLevel: 0
        MeleeWeaponLevel: 0
        MedicineLevel: 3
        ChemistryLevel: 3
        EngineeringLevel: 2
        BuildingLevel: 0
        ResearchLevel: 0
        Atmosphere: true
        Piloting: false
        MusInstruments: true
        Botany: true
        Bureaucracy: true
      - type: AddSkillPoints
        Points: 1

- type: startingGear
  id: CMOGear
  equipment:
    id: CMOPDA
    ears: ClothingHeadsetCMO
    belt: ClothingBeltMedicalFilled
  storage:
    back:
    - Flash