- type: latheRecipePack
  id: SecurityDominators
  recipes:
  - WeaponAssaultDominator
  - WeaponEnergyShotgun
  - WeaponDominator

- type: latheRecipePack
  id: NightVision
  recipes:
  - ClothingEyesNightVisionDeviceEmpty

- type: latheRecipePack
  id: ThermalVision
  recipes:
  - ClothingEyesThermalGlassesEmpty