- type: job
  id: Janitor
  name: job-name-janitor
  description: job-description-janitor
  playTimeTracker: JobJanitor
  startingGear: JanitorGear
  icon: "JobIconJanitor"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Janitor
  - Maintenance
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: GarbageDay
    prototype: WeaponRevolverInspector
  - !type:AddComponentSpecial
    components:
    - type: Skill
      RangeWeaponLevel: 0
      MeleeWeaponLevel: 1
      MedicineLevel: 0
      ChemistryLevel: 2
      EngineeringLevel: 0
      BuildingLevel: 0
      ResearchLevel: 0
      Atmosphere: false
      Piloting: false
      MusInstruments: true
      Botany: false
      Bureaucracy: false
    - type: AddSkillPoints
      Points: 1

- type: startingGear
  id: JanitorGear
  equipment:
    shoes: ClothingShoesGaloshes
    id: JanitorPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
  #storage:
    #back:
    #- Stuff

- type: startingGear
  id: JanitorMaidGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtJanimaid
    id: JanitorPDA
    gloves: ClothingHandsGlovesJanitor
    head: ClothingHeadHatCatEars
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
