# No idea why it's in sci but we ball.
# Why is this one file?
- type: job
  id: StationAi
  name: job-name-station-ai
  description: job-description-station-ai
  playTimeTracker: JobStationAi
  requirements:
  - !type:RoleTimeRequirement
    role: JobBorg
    time: 18000  # 5 hrs
  canBeAntag: false
  icon: JobIconStationAi
  supervisors: job-supervisors-rd
  jobEntity: StationAiBrain
  jobPreviewEntity: PlayerStationAiPreview
  applyTraits: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skill
        RangeWeaponLevel: 3
        MeleeWeaponLevel: 3
        MedicineLevel: 3
        ChemistryLevel: 3
        EngineeringLevel: 3
        Research: true
        Atmosphere: true
        Piloting: true
        MusInstruments: true
        Botany: true
        Bureaucracy: true

- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 72000 #20 hrs
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-rd
  jobEntity: PlayerBorgBattery
  applyTraits: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skill
        RangeWeaponLevel: 3
        MeleeWeaponLevel: 3
        MedicineLevel: 3
        ChemistryLevel: 3
        EngineeringLevel: 3
        Research: true
        InstrumentationLevel: 3
        Atmosphere: true
        Piloting: true
        MusInstruments: true
        Botany: true
        Bureaucracy: true
