- type: job
  id: ResearchAssistant
  name: job-name-research-assistant
  description: job-description-research-assistant
  playTimeTracker: JobResearchAssistant
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 108000 #10 hrs # Corvax-RoleTime
      inverted: true # stop playing intern if you're good at science!
  startingGear: ResearchAssistantGear
  icon: "JobIconResearchAssistant"
  supervisors: job-supervisors-science
  canBeAntag: false
  access:
  - Research
  - Maintenance
  special:
  - !type:AddComponentSpecial 
    components:
      - type: Skill
        RangeWeaponLevel: 0
        MeleeWeaponLevel: 0
        MedicineLevel: 0
        ChemistryLevel: 0
        EngineeringLevel: 2
        BuildingLevel: 0
        ResearchLevel: 3
        Atmosphere: true
        Piloting: false
        MusInstruments: true
        Botany: false
        Bureaucracy: true
      - type: AddSkillPoints
        Points: 1

- type: startingGear
  id: ResearchAssistantGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: ResearchAssistantPDA
    ears: ClothingHeadsetScience
  #  pocket2: BookScientistsGuidebook
  #storage:
    #back:
    #- Stuff
